### ISSUE TITLE
Unable to generate to a new scannable

### ISSUE THREAD

**Issue by jmaleonard** [quikkly/android-sdk#2]
Hi, I am trying to generate a scannable code but no "dots" are appearing on the rendered component. 

I downloaded your test application and the same thing is happening there.

**Comment by greggnogg-quikkly** [comment]
Hi, Thank you for raising this. Could you please clarify which version of Android you are experiencing this issue on, device type and version of the SDK you are using.

We'll take a look and hopefully fix soon!

**Comment by jmaleonard** [comment]
It works for me on Android 7, but not on anything lower. Well the dots are missing on lower versions

**Comment by jmaleonard** [comment]
Hey @greggnogg-quikkly any update on this?

**Comment by greggnogg-quikkly** [comment]
Hi @jmaleonard, We are working on a fix at the moment. Hope to have a fix in the next couple of days. We will update on here when it is ready.

Apologies for the delay and inconvenience!

**Comment by greggnogg-quikkly** [comment]
This issue should now be fixed, however support for API level 19 has been deprecated. At this time Quikkly SDK supports API level 21+. We are working on earlier versions and the readme will be updated to reflect this as/when they are available.
