### ISSUE TITLE
Scanner unable to scan generated scannables

### ISSUE THREAD

**Issue by gauravk95** [quikkly/android-sdk#3]
The Scanner is **unable to scan/detect  any generated scannables** on all android versions.
Also the **dots in scannables are only visible on android nougat and above**. 
Tested the sample app to, but same result.

**Comment by greggnogg-quikkly** [comment]
Please ensure that the Blueprint generated from the developer site is the latest, and you have the latest SDK. Also the blueprint you will generate contains only one detectable design, which will be the one you have selected within the 'Create a Code' page. 

Please also ensure that the blueprint file is located within your assets and accessible from within your package manager before passing the file to Quikkly's SDK.

Alternatively you can specify for Quikkly to use the default blueprint when initialising the SDK. If all the above is confirmed and you still have an issue then we will investigate further and open a support ticket with you.

Best Regards
Gregg

**Comment by greggnogg-quikkly** [comment]
Closing this issue as there is no further information. Please update to the latest SDK and generate a blueprint from our Developer Portal to ensure everything is upto-date
