### ISSUE TITLE
Can't use implements QuikklyUi.Listener

### ISSUE THREAD

**Issue by wiaamLB** [quikkly/android-sdk#4]
hello why i can't use QuikklyUI library

**Comment by Greggnogg-Hive** [comment]
Please could you post a snippet of your code and the error you are seeing? Also would be helpful to understand your use case. Please contact us through the support form for specific support requests around usage: https://quikklycodes.com/contact

**Comment by greggnogg-quikkly** [comment]
Please provide more details. If this is a general question then please submit a support request through our developer portal or website: https://quikklycodes.com/contact
